journal_api_create:
    path: /_automation/journal
    controller: App\JournalApiController::create
    methods: [POST]

journal_api_update:
    path: /_automation/journal/{id}
    controller: App\JournalApiController::update
    methods: [PATCH]
    requirements:
        id: '\d+'
